# Exact grouped-RTN hierarchy for averaged density matrices.
# The zeroth hierarchy component, rho_r with r = (0,...,0), is the physical
# noise-averaged density matrix.

struct RTNGroupedDensityParams
    H0::Matrix{ComplexF64}
    P::Matrix{ComplexF64}
    gammas::Vector{Float64}
    deltas::Vector{Float64}
    counts::Vector{Int}
    dims::Vector{Int}
    strides::Vector{Int}
    lindblad_ops::Vector{Matrix{ComplexF64}}
    lindblad_rates::Vector{Float64}
    lindblad_l2::Vector{Matrix{ComplexF64}}
    d::Int
    K::Int
    m::Int
end

function make_rtn_grouped_density_params(
    H0,
    P,
    gammas,
    deltas,
    counts;
    lindblad_ops = Matrix{ComplexF64}[],
    lindblad_rates = Float64[]
)
    K = length(counts)

    @assert length(gammas) == K
    @assert length(deltas) == K
    @assert all(counts .>= 1)
    @assert all(gammas .> 0)

    H0c = ComplexF64.(H0)
    Pc = ComplexF64.(P)

    d = size(H0c, 1)
    @assert size(H0c, 2) == d
    @assert size(Pc) == (d, d)

    ops = [ComplexF64.(L) for L in lindblad_ops]

    if isempty(lindblad_rates) && !isempty(ops)
        rates = ones(Float64, length(ops))
    else
        rates = Float64.(lindblad_rates)
    end

    @assert length(ops) == length(rates)
    @assert all(rates .>= 0)

    for L in ops
        @assert size(L) == (d, d)
    end

    l2 = [Matrix(L' * L) for L in ops]

    dims = Int.(counts .+ 1)
    strides = ones(Int, K)
    for q in 2:K
        strides[q] = strides[q - 1] * dims[q - 1]
    end

    m = prod(dims)

    return RTNGroupedDensityParams(
        H0c,
        Pc,
        Float64.(gammas),
        Float64.(deltas),
        Int.(counts),
        dims,
        strides,
        ops,
        rates,
        l2,
        d,
        K,
        m
    )
end

function _add_lindblad_density_terms!(drho, rho, p::RTNGroupedDensityParams)
    @inbounds for a in eachindex(p.lindblad_ops)
        L = p.lindblad_ops[a]
        L2 = p.lindblad_l2[a]
        rate = p.lindblad_rates[a]

        drho .+= rate .* (L * rho * L' .- 0.5 .* (L2 * rho .+ rho * L2))
    end

    return nothing
end

function rtn_grouped_density_rhs!(du, u, p::RTNGroupedDensityParams, t)
    R = reshape(u, p.d, p.d, p.m)
    DR = reshape(du, p.d, p.d, p.m)

    @inbounds for idx in 1:p.m
        idx0 = idx - 1

        rho = @view R[:, :, idx]
        drho = @view DR[:, :, idx]

        # Deterministic Liouville-von Neumann evolution: -i[H0, rho].
        drho .= (-1im) .* (p.H0 * rho .- rho * p.H0)

        # Optional trace-preserving Lindblad dissipators.
        if !isempty(p.lindblad_ops)
            _add_lindblad_density_terms!(drho, rho, p)
        end

        # Switching damping: -2 sum_q gamma_q r_q rho_r.
        x = idx0
        damping = 0.0

        for q in 1:p.K
            rq = x % p.dims[q]
            x ÷= p.dims[q]
            damping += 2.0 * p.gammas[q] * rq
        end

        if damping != 0.0
            drho .-= damping .* rho
        end

        # RTN hierarchy couplings generated by -i delta_q [P, rho].
        x = idx0

        for q in 1:p.K
            rq = x % p.dims[q]
            x ÷= p.dims[q]

            stride = p.strides[q]

            if rq > 0
                rhom = @view R[:, :, idx - stride]
                drho .+= (-1im * p.deltas[q] * rq) .* (p.P * rhom .- rhom * p.P)
            end

            if rq < p.counts[q]
                rhop = @view R[:, :, idx + stride]
                drho .+= (-1im * p.deltas[q] * (p.counts[q] - rq)) .* (p.P * rhop .- rhop * p.P)
            end
        end
    end

    return nothing
end

function solve_rtn_density_matrices(
    counts,
    gammas,
    deltas;
    H0,
    P,
    rho0,
    tmax = 40.0,
    nt = 1000,
    alg = Tsit5(),
    reltol = 1e-8,
    abstol = 1e-10,
    lindblad_ops = Matrix{ComplexF64}[],
    lindblad_rates = Float64[],
    check_initial_state = true
)
    params = make_rtn_grouped_density_params(
        H0,
        P,
        gammas,
        deltas,
        counts;
        lindblad_ops = lindblad_ops,
        lindblad_rates = lindblad_rates
    )

    rho0c = ComplexF64.(rho0)
    @assert size(rho0c) == (params.d, params.d)

    if check_initial_state
        @assert isapprox(rho0c, rho0c'; atol = 1e-10) "rho0 should be Hermitian."
        @assert isapprox(real(tr(rho0c)), 1.0; atol = 1e-10) "rho0 should have trace one."
    end

    U0 = zeros(ComplexF64, params.d, params.d, params.m)
    U0[:, :, 1] .= rho0c

    ts = collect(range(0.0, tmax, length = nt))

    prob = ODEProblem(
        rtn_grouped_density_rhs!,
        vec(U0),
        (0.0, tmax),
        params
    )

    sol = solve(
        prob,
        alg;
        saveat = ts,
        reltol = reltol,
        abstol = abstol
    )

    rhos = zeros(ComplexF64, params.d, params.d, length(sol.t))

    for i in eachindex(sol.u)
        R = reshape(sol.u[i], params.d, params.d, params.m)
        rhos[:, :, i] .= @view R[:, :, 1]
    end

    return sol.t, rhos, sol, params
end
