include("utils.jl")

# Convert the time-domain dipole coherence generated by the RTN hierarchy into a frequency-domain
# absorption spectrum through a numerically evaluated one-sided Fourier transform.
function absorption_spectrum(
    ts::AbstractVector{<:Real},
    response::AbstractVector{<:Complex};
    wmin = -6.0,
    wmax = 6.0,
    nw = 1201,
    normalize = true
)
    @assert length(ts) == length(response)

    ws = collect(range(wmin, wmax, length = nw))
    weights = trapezoid_weights(ts)
    A = zeros(Float64, nw)

    @inbounds for iw in eachindex(ws)
        omega = ws[iw]
        integral = 0.0 + 0.0im

        for it in eachindex(ts)
            integral += weights[it] * exp(1im * omega * ts[it]) * response[it]
        end

        A[iw] = real(integral) / pi
    end

    if normalize
        safe_normalize!(A)
    end

    return ws, A
end